# Generated by Django 4.1.3 on 2023-05-27 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_department', models.CharField(blank='True', max_length=100, verbose_name='Цех')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(verbose_name='Приоритет выполнения')),
                ('processing_times', models.PositiveIntegerField(verbose_name='Время выполнения процесса')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.PositiveIntegerField(verbose_name='From')),
                ('to_stage', models.PositiveIntegerField(verbose_name='To')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_machine', models.TextField(max_length=100, verbose_name='Машина')),
                ('description', models.TextField(verbose_name='Пояснение')),
                ('id_department', models.PositiveIntegerField(verbose_name='Id Department')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='ObtainedResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('job', models.IntegerField()),
                ('name_job', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_dates', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('processing_times', models.IntegerField()),
                ('machine_id', models.IntegerField()),
                ('name_machine', models.CharField(max_length=255)),
                ('description_machine', models.TextField()),
                ('T_i', models.DateField()),
                ('T_c', models.DateField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ObtainedResultMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.PositiveIntegerField(verbose_name='Id Department')),
                ('department_name', models.CharField(max_length=255, verbose_name='Department Name')),
                ('machine', models.PositiveIntegerField()),
                ('name_machine', models.CharField(max_length=255)),
                ('description_machine', models.TextField()),
                ('job', models.PositiveIntegerField()),
                ('job_name', models.CharField(max_length=255)),
                ('descripiton_job', models.TextField()),
                ('T_i', models.DateField()),
                ('T_c', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JobName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_job', models.CharField(blank='True', max_length=100, verbose_name='Работа')),
                ('description', models.TextField(verbose_name='Пояснение')),
                ('due_dates', models.DateField(blank='True', verbose_name='Due dates')),
                ('id_department', models.PositiveIntegerField(verbose_name='Id Department')),
                ('explanation', models.ManyToManyField(related_name='explanation', to='app.job')),
                ('links', models.ManyToManyField(related_name='links', to='app.links')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.machine', verbose_name='Машина'),
        ),
    ]
