# Generated by Django 4.1.3 on 2023-05-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_department_job_links_machine_obtainedresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obtainedresultmachine',
            name='stage',
            field=models.PositiveIntegerField(default=0, verbose_name='Id Stage'),
            preserve_default=False,
        ),
    ]
