# Generated by Django 4.1.3 on 2023-05-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_obtainedresultmachine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obtainedresultmachine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
