# Generated by Django 4.1.3 on 2023-05-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_obtainedresultmachine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obtainedresultmachine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
